export * from "./BaseResponse/BaseResponse";
export * from "./NivelAcademico/NivelAcademico";
export * from "./Facultad/Facultad";
export * from "./ProgramaAcademico/ProgramaAcademico";
export * from "./Inscripcion/Inscripcion";
export * from "./HistorialCambio/HistorialCambio";
export * from "./RecursoAcademico/RecursoAcademico";
export * from "./Curso/curso";
export * from "./CursoRecursoAcademico/cursoRecursoAcademico";
